# 데이터 전처리 EX-5 : 데이터 스케일링

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler, MinMaxScaler, LabelEncoder, OneHotEncoder

df = pd.read_csv('winequality-red.csv')

df.head()

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5

In [3]:
scaler = StandardScaler()

cols = ['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar', 'chlorides']

for col in cols:
    df[col] = scaler.fit_transform(df[[col]])

df

,fixed acidity,volatile acidity,citric acid,residual sugar,chlorides,free sulfur dioxide,total sulfur dioxide,density,pH,sulphates,alcohol,quality
0,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,11.0,34.0,0.99780,3.51,0.56,9.4,5
1,-0.298547,1.967442,-1.391472,0.043416,0.223875,25.0,67.0,0.99680,3.20,0.68,9.8,5
2,-0.298547,1.297065,-1.186070,-0.169427,0.096353,15.0,54.0,0.99700,3.26,0.65,9.8,5
3,1.654856,-1.384443,1.484154,-0.453218,-0.264960,17.0,60.0,0.99800,3.16,0.58,9.8,6
4,-0.528360,0.961877,-1.391472,-0.453218,-0.243707,11.0,34.0,0.99780,3.51,0.56,9.4,5
...,...,...,...,...,...,...,...,...,...,...,...,...
1594,-1.217796,0.403229,-0.980669,-0.382271,0.053845,32.0,44.0,0.99490,3.45,0.58,10.5,5
1595,-1.390155,0.123905,-0.877968,-0.240375,-0.541259,39.0,51.0,0.99512,3.52,0.76,11.2,6
1596,-1.160343,-0.099554,-0.723916,-0.169427,-0.243707,29.0,40.0,0.99574,3.42,0.75,11.0,6
1597,-1.390155,0.654620,-0.775267,-0.382271,-0.264960,32.0,44.0,0.99547,3.57,0.71,10.2,5
1598,-1.332702,-1.216849,1.021999,0.752894,-0.434990,18.0,42.0,0.99549,3.39,0.66,11.0,6